"""
Mở rộng tri thức RAG TOÀN DIỆN trong scope dự án (Network SOC / Intrusion Detection).
Bổ sung một tập lớn kỹ thuật MITRE ATT&CK phủ đủ 14 tactic + playbook NIST.

Idempotent. Sau khi chạy: BẮT BUỘC rebuild index:
    .venv/bin/python -c "from src.rag.embedder import update_checksums_file, build_all_indexes; update_checksums_file(); build_all_indexes()"
"""


def _tech(tid, name, tactic, desc, det, logp, resp):
    return {
        "id": tid, "name": name, "tactic": tactic, "description": desc,
        "detection_indicators": det + [tid],
        "log_patterns": logp,
        "response_actions": resp,
    }


# Tập kỹ thuật bổ sung toàn diện theo từng tactic (SOC-relevant)
EXPANDED_MITRE = [
    # ---------- RECONNAISSANCE ----------
    _tech("T1595", "Active Scanning", "Reconnaissance",
          "Adversaries may execute active reconnaissance scans to gather information that can be used during targeting, scanning victim infrastructure via IP blocks, vulnerability scanning, or wordlist scanning of web content.",
          ["vulnerability scanner signatures", "web content/path wordlist scanning", "IP block sweeps"],
          ["scanner user-agents (nmap, nikto, nuclei)", "bursts of 404s from path fuzzing", "broad IP-range probing"],
          ["block scanning source at edge", "fingerprint scanner tooling", "watch targeted assets for exploitation"]),
    _tech("T1595.002", "Active Scanning: Vulnerability Scanning", "Reconnaissance",
          "Adversaries may scan victims for vulnerabilities that can be used during targeting, checking for specific software versions and configurations against known CVE databases.",
          ["version-probing requests", "CVE-targeted scan patterns"],
          ["requests probing known-vulnerable paths/versions", "scanner fingerprint in user-agent"],
          ["patch exposed vulnerable services", "block scanner IPs", "harden version disclosure"]),
    _tech("T1592", "Gather Victim Host Information", "Reconnaissance",
          "Adversaries may gather information about the victim's hosts (hardware, software, firmware, configuration) used during targeting.",
          ["banner grabbing", "OS/service fingerprinting"],
          ["service banner enumeration", "fingerprint probes to many services"],
          ["minimize banner/version disclosure", "alert on enumeration patterns"]),
    _tech("T1590", "Gather Victim Network Information", "Reconnaissance",
          "Adversaries may gather information about the victim's networks (IP ranges, domains, topology, DNS) used during targeting.",
          ["DNS enumeration", "WHOIS/range lookups", "subdomain brute forcing"],
          ["high-volume DNS queries enumerating zone", "AXFR zone-transfer attempts"],
          ["restrict zone transfers", "rate-limit DNS", "monitor subdomain enumeration"]),

    # ---------- RESOURCE DEVELOPMENT ----------
    _tech("T1584", "Compromise Infrastructure", "Resource Development",
          "Adversaries may compromise third-party infrastructure (servers, domains, botnets) that can be used during targeting, blending C2 with legitimate-looking sources.",
          ["traffic to compromised legitimate hosts", "newly-malicious known-good domains"],
          ["beaconing to previously-benign domains", "C2 on compromised CDN/host"],
          ["block confirmed-compromised infra", "share IOCs to threat intel"]),
    _tech("T1588", "Obtain Capabilities", "Resource Development",
          "Adversaries may buy and/or steal capabilities (malware, exploits, certificates, tools) that can be used during targeting.",
          ["use of commodity malware/exploit kits", "stolen code-signing certs"],
          ["known malware family signatures", "exploit-kit landing patterns"],
          ["block known tooling hashes/certs", "update detection content"]),

    # ---------- INITIAL ACCESS ----------
    _tech("T1566", "Phishing", "Initial Access",
          "Adversaries may send phishing messages to gain access to victim systems, via malicious attachments or links (spearphishing).",
          ["malicious email links/attachments", "credential-harvesting landing pages"],
          ["clicks to known-malicious URLs from corp net", "macro-enabled attachment execution"],
          ["purge malicious email org-wide", "block sender/URL", "reset credentials of clickers"]),
    _tech("T1199", "Trusted Relationship", "Initial Access",
          "Adversaries may breach or otherwise leverage organizations who have access to intended victims, abusing trusted third-party/VPN/MSP connections.",
          ["access via trusted partner/VPN connection", "anomalous third-party account activity"],
          ["partner-network access outside normal pattern", "MSP account anomalies"],
          ["scope and revoke trusted access", "enforce least-privilege for partners"]),
    _tech("T1189", "Drive-by Compromise", "Initial Access",
          "Adversaries may gain access through a user visiting a compromised website, exploiting the browser for code execution.",
          ["browser exploitation traffic", "redirect to exploit kit"],
          ["malicious iframe/redirect chains", "exploit-kit traffic to client"],
          ["block malicious domains", "patch browsers", "isolate affected client"]),

    # ---------- EXECUTION ----------
    _tech("T1203", "Exploitation for Client Execution", "Execution",
          "Adversaries may exploit software vulnerabilities in client applications (browsers, office apps, readers) to execute code.",
          ["malformed documents/exploits", "client app crash + spawn"],
          ["office app spawning shell/script host", "exploit payload in document"],
          ["patch client software", "isolate host", "block delivery vector"]),
    _tech("T1053", "Scheduled Task/Job", "Execution",
          "Adversaries may abuse task scheduling (cron, at, Windows Task Scheduler) to execute malicious code, often for persistence as well.",
          ["new/unusual scheduled tasks", "cron entries spawning network connections"],
          ["creation of scheduled task running script/binary", "cron job with C2 callout"],
          ["remove malicious tasks", "audit scheduled-task creation", "baseline legitimate jobs"]),
    _tech("T1059.001", "Command and Scripting Interpreter: PowerShell", "Execution",
          "Adversaries may abuse PowerShell for execution, including download-and-execute, encoded commands, and in-memory operation to evade detection.",
          ["encoded/obfuscated PowerShell", "PowerShell downloading from internet"],
          ["powershell -enc / -nop / IEX (New-Object Net.WebClient)", "EncodedCommand usage"],
          ["enable PowerShell script-block logging", "constrained language mode", "isolate host"]),

    # ---------- PERSISTENCE ----------
    _tech("T1505.003", "Server Software Component: Web Shell", "Persistence",
          "Adversaries may backdoor web servers with web shells to establish persistent access, executing commands via crafted HTTP requests.",
          ["web shell files in web root", "command execution via HTTP params"],
          ["POST to suspicious .php/.jsp/.aspx with cmd params", "web server spawning shell"],
          ["quarantine the web shell file", "block source IP at WAF", "audit web root integrity"]),
    _tech("T1098", "Account Manipulation", "Persistence",
          "Adversaries may manipulate accounts (add credentials, modify permissions, add to groups) to maintain access.",
          ["unexpected privilege/group changes", "new credentials added to account"],
          ["account added to admin group", "new SSH key / app password added"],
          ["revert unauthorized changes", "rotate credentials", "audit privileged group membership"]),
    _tech("T1136", "Create Account", "Persistence",
          "Adversaries may create accounts to maintain access to victim systems (local, domain, or cloud).",
          ["unexpected new account creation", "rogue admin accounts"],
          ["new user/admin account outside change process", "service account creation anomaly"],
          ["disable rogue accounts", "alert on account creation", "review IAM change logs"]),
    _tech("T1547", "Boot or Logon Autostart Execution", "Persistence",
          "Adversaries may configure system settings to automatically execute a program during boot or logon (registry run keys, startup folder, services).",
          ["new autostart registry/services entries", "startup-folder implants"],
          ["modification of Run keys / startup items", "new auto-start service"],
          ["remove malicious autostart entries", "baseline autostart locations"]),

    # ---------- PRIVILEGE ESCALATION ----------
    _tech("T1068", "Exploitation for Privilege Escalation", "Privilege Escalation",
          "Adversaries may exploit software vulnerabilities to elevate privileges, taking advantage of kernel or service bugs to gain SYSTEM/root.",
          ["local privilege-escalation exploit", "kernel exploit indicators"],
          ["process unexpectedly running as SYSTEM/root", "known privesc CVE exploitation"],
          ["patch vulnerable component", "isolate host", "hunt for follow-on actions"]),
    _tech("T1548", "Abuse Elevation Control Mechanism", "Privilege Escalation",
          "Adversaries may circumvent mechanisms designed to control elevated privileges (sudo, UAC, setuid) to gain higher-level permissions.",
          ["sudo/UAC bypass patterns", "setuid abuse"],
          ["unexpected sudo usage", "UAC-bypass technique execution"],
          ["audit sudoers/UAC config", "restrict elevation paths"]),
    _tech("T1134", "Access Token Manipulation", "Privilege Escalation",
          "Adversaries may modify access tokens to operate under a different user or system security context to escalate privileges or bypass access controls.",
          ["token theft/impersonation", "process running with stolen token"],
          ["token duplication/impersonation API usage", "privilege context change"],
          ["isolate host", "rotate impacted credentials", "audit token-manipulation events"]),

    # ---------- DEFENSE EVASION (mapped to KB tactic 'Stealth') ----------
    _tech("T1070", "Indicator Removal", "Stealth",
          "Adversaries may delete or modify artifacts (logs, files, command history) to remove evidence of their presence and hinder detection.",
          ["log clearing", "shell history deletion", "timestomping"],
          ["Windows event log cleared (1102)", "auth.log/secure truncated", "history file emptied"],
          ["forward logs off-host (immutable)", "alert on log-clearing", "restore from backups"]),
    _tech("T1027", "Obfuscated Files or Information", "Stealth",
          "Adversaries may obfuscate/encode files or commands (base64, packing, encryption) to evade detection and analysis.",
          ["base64/packed payloads", "high-entropy content"],
          ["encoded command-lines", "packed binaries with high entropy"],
          ["deobfuscate and analyze", "entropy-based detection", "isolate host"]),
    _tech("T1562", "Impair Defenses", "Defense Impairment",
          "Adversaries may modify/disable security tools (AV, EDR, firewall, logging) to avoid detection and enable their operations.",
          ["security service stopped/disabled", "firewall/AV tampering"],
          ["EDR/AV service stop", "firewall rule deletion", "logging disabled"],
          ["re-enable and alert on defense tampering", "tamper-protect security tools", "isolate host"]),
    _tech("T1036", "Masquerading", "Stealth",
          "Adversaries may manipulate features of their artifacts to appear legitimate (renaming malware to system process names, fake extensions).",
          ["process name/path mismatch", "system-process impersonation"],
          ["svchost/lsass running from wrong path", "double-extension files"],
          ["compare process path/hash to baseline", "alert on masquerading", "quarantine artifact"]),
    _tech("T1497", "Virtualization/Sandbox Evasion", "Stealth",
          "Adversaries may employ checks to detect and avoid virtualization and analysis environments, delaying or altering behavior in sandboxes.",
          ["sandbox/VM detection checks", "execution stalling/delays"],
          ["VM-artifact checks", "long sleeps before payload"],
          ["use hardened analysis env", "extend detonation time", "behavioral detection"]),

    # ---------- CREDENTIAL ACCESS ----------
    _tech("T1003", "OS Credential Dumping", "Credential Access",
          "Adversaries may dump credentials from the OS and software (LSASS memory, SAM, /etc/shadow, NTDS.dit) to obtain account logins for movement.",
          ["LSASS memory access", "SAM/NTDS access", "credential dumping tools"],
          ["procdump/mimikatz on lsass", "shadow/SAM file read", "NTDS.dit extraction"],
          ["rotate exposed credentials", "enable Credential Guard", "isolate and investigate"]),
    _tech("T1555", "Credentials from Password Stores", "Credential Access",
          "Adversaries may search for and obtain credentials from password stores (browsers, keychains, password managers).",
          ["access to browser/keychain credential stores", "password-manager DB access"],
          ["read of browser login data DB", "keychain/credential vault access"],
          ["rotate stored credentials", "alert on credential-store access", "isolate host"]),
    _tech("T1552", "Unsecured Credentials", "Credential Access",
          "Adversaries may search compromised systems for insecurely stored credentials (config files, scripts, history, cloud metadata).",
          ["credentials in plaintext files/scripts", "cloud metadata credential access"],
          ["grep for password/secret in files", "access to 169.254.169.254 metadata"],
          ["remove hardcoded secrets, use vaults", "restrict metadata access", "rotate exposed keys"]),
    _tech("T1557", "Adversary-in-the-Middle", "Credential Access",
          "Adversaries may position between networked devices (ARP spoofing, LLMNR/NBT-NS poisoning, rogue DHCP) to intercept credentials/traffic.",
          ["ARP spoofing", "LLMNR/NBT-NS poisoning", "rogue gateway"],
          ["gratuitous ARP anomalies", "LLMNR/NBT-NS response from non-DNS host", "MAC-IP binding changes"],
          ["enable dynamic ARP inspection", "disable LLMNR/NBT-NS", "isolate rogue host"]),

    # ---------- DISCOVERY ----------
    _tech("T1083", "File and Directory Discovery", "Discovery",
          "Adversaries may enumerate files and directories to find information of interest before collection/exfiltration.",
          ["recursive directory listing", "search for sensitive file types"],
          ["mass dir/file enumeration", "search for *.kdbx/*.pem/*.config"],
          ["alert on mass enumeration", "monitor sensitive-file access"]),
    _tech("T1087", "Account Discovery", "Discovery",
          "Adversaries may enumerate accounts (local, domain, cloud, email) to understand the environment and plan further actions.",
          ["enumeration of users/groups", "LDAP/AD account queries"],
          ["net user/net group enumeration", "bulk LDAP account queries"],
          ["alert on bulk account enumeration", "limit directory read access"]),
    _tech("T1135", "Network Share Discovery", "Discovery",
          "Adversaries may look for shared folders and drives on remote systems to identify data and lateral-movement targets.",
          ["SMB share enumeration", "net view / share scans"],
          ["enumeration of network shares", "SMB tree-connect sweep"],
          ["audit share permissions", "alert on share enumeration"]),
    _tech("T1049", "System Network Connections Discovery", "Discovery",
          "Adversaries may enumerate active network connections to/from a system to understand the environment and identify pivots.",
          ["netstat / connection enumeration", "active session listing"],
          ["netstat/ss execution", "enumeration of established sessions"],
          ["baseline normal discovery", "alert on recon from non-admin hosts"]),

    # ---------- LATERAL MOVEMENT ----------
    _tech("T1550", "Use Alternate Authentication Material", "Lateral Movement",
          "Adversaries may use stolen authentication material (hashes, tickets, tokens) to move laterally without the plaintext password (pass-the-hash/ticket).",
          ["pass-the-hash/ticket patterns", "NTLM relay", "Kerberos ticket reuse"],
          ["overpass-the-hash logon", "PtH NTLM auth from unusual host", "golden/silver ticket usage"],
          ["rotate krbtgt and impacted creds", "enable Credential Guard", "monitor anomalous Kerberos"]),
    _tech("T1563", "Remote Service Session Hijacking", "Lateral Movement",
          "Adversaries may take control of preexisting remote sessions (RDP, SSH) to move laterally using already-authenticated access.",
          ["hijacked RDP/SSH session", "session takeover patterns"],
          ["RDP session reconnect anomaly", "SSH session multiplexing abuse"],
          ["terminate suspicious sessions", "alert on session hijack", "isolate hosts"]),

    # ---------- COLLECTION ----------
    _tech("T1005", "Data from Local System", "Collection",
          "Adversaries may search local system sources (file systems, databases) to collect data of interest prior to exfiltration.",
          ["bulk local data access", "staging of collected files"],
          ["mass read of documents/DB files", "archive creation before exfil"],
          ["DLP on sensitive data", "alert on bulk collection", "investigate staging"]),
    _tech("T1119", "Automated Collection", "Collection",
          "Adversaries may use automated techniques (scripts) to gather internal data, often with other discovery techniques.",
          ["scripted mass collection", "scheduled data gathering"],
          ["automated archive of many files", "loop-based file collection"],
          ["alert on automated collection patterns", "DLP and access monitoring"]),
    _tech("T1039", "Data from Network Shared Drive", "Collection",
          "Adversaries may search network shares on remote systems to collect data prior to exfiltration.",
          ["bulk access to network shares", "copying from file servers"],
          ["mass file reads from SMB shares", "staging from network drives"],
          ["audit share access", "DLP on file servers", "alert on bulk share reads"]),

    # ---------- COMMAND AND CONTROL ----------
    _tech("T1105", "Ingress Tool Transfer", "Command And Control",
          "Adversaries may transfer tools or files from an external system into a compromised environment (download via C2, certutil, curl/wget).",
          ["download of tooling from internet", "LOLBin file download"],
          ["certutil/bitsadmin/curl downloading executable", "tool transfer over C2"],
          ["block download sources", "alert on LOLBin downloads", "quarantine transferred tools"]),
    _tech("T1573", "Encrypted Channel", "Command And Control",
          "Adversaries may employ encryption to conceal C2 traffic (TLS, custom crypto), blending with normal encrypted traffic.",
          ["TLS C2 to suspicious endpoints", "custom-encrypted beacon"],
          ["self-signed/JA3-anomalous TLS to C2", "periodic encrypted beacon"],
          ["TLS inspection/JA3 fingerprinting", "block C2 destinations", "isolate host"]),
    _tech("T1568", "Dynamic Resolution", "Command And Control",
          "Adversaries may dynamically establish C2 by changing infrastructure (DGA, fast flux, DNS calculation) to evade blocking.",
          ["DGA domains", "fast-flux DNS", "high NXDOMAIN rate"],
          ["many algorithmically-generated domain lookups", "rapidly-changing A records"],
          ["DGA detection and DNS sinkholing", "block resolved C2 IPs"]),
    _tech("T1090.003", "Proxy: Multi-hop Proxy (TOR)", "Command And Control",
          "Adversaries may chain multiple proxies (e.g., TOR) to disguise the source of malicious traffic and evade attribution.",
          ["traffic to TOR entry/exit nodes", "multi-hop relay chains"],
          ["connections to known TOR nodes", "chained proxy hops"],
          ["block TOR infrastructure", "alert on anonymization-network use"]),

    # ---------- EXFILTRATION ----------
    _tech("T1567", "Exfiltration Over Web Service", "Exfiltration",
          "Adversaries may use legitimate external web services (cloud storage, paste sites, code repos) to exfiltrate data, blending with normal traffic.",
          ["upload to cloud storage/paste sites", "data to code repositories"],
          ["large uploads to pastebin/dropbox/github", "exfil to web service API"],
          ["DLP on web-service uploads", "restrict/monitor cloud egress", "block confirmed exfil services"]),
    _tech("T1030", "Data Transfer Size Limits", "Exfiltration",
          "Adversaries may exfiltrate data in fixed-size chunks (instead of whole files) to avoid triggering volume-based alerts.",
          ["uniform-sized periodic transfers", "chunked exfiltration"],
          ["repeated equal-sized outbound transfers", "low-and-slow exfil pattern"],
          ["correlate chunked transfers over time", "DLP on cumulative volume"]),
    _tech("T1020", "Automated Exfiltration", "Exfiltration",
          "Adversaries may exfiltrate data using automated processing after it has been collected.",
          ["scripted/scheduled exfiltration", "automated upload routines"],
          ["scheduled outbound transfer jobs", "automated exfil after collection"],
          ["alert on automated exfil patterns", "DLP and egress monitoring"]),

    # ---------- IMPACT ----------
    _tech("T1486", "Data Encrypted for Impact", "Impact",
          "Adversaries may encrypt data on target systems (ransomware) to interrupt availability and extort the victim.",
          ["mass file encryption", "ransom notes", "shadow-copy deletion"],
          ["rapid file modification/rename to encrypted extensions", "vssadmin delete shadows", "ransom note creation"],
          ["isolate affected hosts immediately", "restore from offline backups", "block ransomware C2/spread"]),
    _tech("T1490", "Inhibit System Recovery", "Impact",
          "Adversaries may delete or disable recovery features (shadow copies, backups, recovery console) to maximize impact of destructive attacks.",
          ["shadow copy/backup deletion", "recovery disabled"],
          ["vssadmin/wbadmin delete", "bcdedit recovery disable"],
          ["maintain offline immutable backups", "alert on recovery tampering"]),
    _tech("T1489", "Service Stop", "Impact",
          "Adversaries may stop or disable services to render systems unusable or to aid further attacks (e.g., stopping DBs before ransomware).",
          ["critical services stopped", "DB/backup services killed"],
          ["mass service stop", "termination of database/security services"],
          ["alert on critical-service stop", "restore services", "investigate intent"]),
    _tech("T1496", "Resource Hijacking", "Impact",
          "Adversaries may leverage victim resources (CPU/GPU) for cryptomining or other compute-intensive tasks, degrading availability.",
          ["cryptomining traffic/processes", "sustained high CPU/GPU"],
          ["connections to mining pools", "miner process/user-agent"],
          ["block mining pools", "kill miner and isolate host", "investigate initial access"]),
]


# NIST playbook bổ sung thêm
EXPANDED_NIST = [
    {
        "control": "NIST.IR.RANSOMWARE",
        "name": "Ransomware Incident Response Playbook",
        "domain": "Incident Response Life Cycle",
        "description": "Playbook for ransomware (MITRE T1486 Data Encrypted for Impact, T1490 Inhibit System Recovery, T1489 Service Stop) where data is encrypted for extortion.",
        "applicability": "Relevant when detecting rapid mass file encryption, ransom notes, shadow-copy/backup deletion, or service-stop activity preceding encryption.",
        "response_guidance": "DETECTION & ANALYSIS: Identify patient-zero, encryption scope, and ransomware family. CONTAINMENT: Immediately isolate affected hosts from the network (keep powered on for forensics), block spread via SMB/admin shares, and disable affected accounts. ERADICATION & RECOVERY: Remove the ransomware, rebuild encrypted hosts, and restore from OFFLINE/immutable backups (do NOT pay). POST-INCIDENT: Close the initial-access vector, enforce offline backups + EDR, and segment to limit blast radius.",
    },
    {
        "control": "NIST.IR.CREDACCESS",
        "name": "Credential Theft & Dumping Playbook",
        "domain": "Incident Response Life Cycle",
        "description": "Playbook for credential access (MITRE T1003 OS Credential Dumping, T1555 Password Stores, T1552 Unsecured Credentials, T1557 AiTM) where account secrets are stolen.",
        "applicability": "Relevant when detecting LSASS/SAM/shadow access, credential-store reads, ARP/LLMNR poisoning, or use of cracked/dumped credentials.",
        "response_guidance": "DETECTION & ANALYSIS: Determine which credentials were exposed and how. CONTAINMENT: Force-reset and revoke sessions for all exposed accounts, enforce MFA, and isolate the dumping host. ERADICATION & RECOVERY: Rotate service/domain credentials (krbtgt twice if DC affected), enable Credential Guard, and remove the dumping tooling. POST-INCIDENT: Deploy LSASS protection, disable LLMNR/NBT-NS, and monitor for pass-the-hash/ticket.",
    },
    {
        "control": "NIST.IR.WEBSHELL",
        "name": "Web Shell & Server Backdoor Playbook",
        "domain": "Incident Response Life Cycle",
        "description": "Playbook for web shells / server software component backdoors (MITRE T1505.003) providing persistent command execution on web servers.",
        "applicability": "Relevant when detecting suspicious files in web roots, command execution via HTTP parameters, or web servers spawning shells.",
        "response_guidance": "DETECTION & ANALYSIS: Locate the web shell file(s) and review web/access logs for the upload vector and commands executed. CONTAINMENT: Quarantine the web shell, block the attacker IP at the WAF, and take the affected app offline if active compromise. ERADICATION & RECOVERY: Patch the exploited web vulnerability, audit web-root integrity, and rebuild if backdoors are widespread. POST-INCIDENT: Add file-integrity monitoring on web roots and WAF rules for the exploit.",
    },
]


# NOTE: file này giờ là MODULE DỮ LIỆU thuần (chỉ export EXPANDED_MITRE / EXPANDED_NIST).
# Entry point xây dựng tri thức DUY NHẤT là `scripts/build_knowledge_base.py` (gộp cả
# nguồn này + supplement_knowledge_base + rebuild index trong 1 lần).
